[project]
name = "bedrock-code-agent"
version = "0.1.0"
description = "Amazon Bedrock Agent for code generation"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.36.0",
    "ipykernel>=6.29.5",
    "litellm>=1.58.2",
]
